version: "3.9"
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: 1qaz2wsx
    hostname: minio
    command: server --console-address ":9001" /data
    volumes:
      - ./minio-data:/data

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1qaz2wsx
      PGDATA: /var/lib/postgresql/data/pgdata  
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  webapp:
    build: .
    image: easy_storage_webapp
    ports:
      - "8080:8080"
